apiVersion: v1
kind: Service
metadata:
  name: grpcui
spec:
  selector:
    app.kubernetes.io/name: grpcui
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpcui
  labels:
    app.kubernetes.io/name: grpcui
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: grpcui
  template:
    metadata:
      labels:
        app.kubernetes.io/name: grpcui
    spec:
      containers:
        - name: grpcui
          image: fullstorydev/grpcui:v1.4.2
          args: ["-plaintext", "-port", "8080", "service-template:8080"]
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
            - name: grpcui_JSON_URL
              value: http://localhost:8080/api/docs/book/v1/book.grpcui.json
