apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: fotiadism-local
image: rancher/k3s:v1.32.1-k3s1
registries:
  create:
    name: fotiadism-local-registry
    host: 0.0.0.0
    hostPort: "5000"
