// Code generated by mockery v2.30.1. DO NOT EDIT.

package mock

import (
	context "context"

	queries "github.com/FotiadisM/mock-microservice/internal/store/queries"
	mock "github.com/stretchr/testify/mock"

	sql "database/sql"

	store "github.com/FotiadisM/mock-microservice/internal/store"

	uuid "github.com/google/uuid"
)

// MockStore is an autogenerated mock type for the Store type
type MockStore struct {
	mock.Mock
}

type MockStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStore) EXPECT() *MockStore_Expecter {
	return &MockStore_Expecter{mock: &_m.Mock}
}

// CreateUser provides a mock function with given fields: ctx, arg
func (_m *MockStore) CreateUser(ctx context.Context, arg queries.CreateUserParams) (queries.User, error) {
	ret := _m.Called(ctx, arg)

	var r0 queries.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, queries.CreateUserParams) (queries.User, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, queries.CreateUserParams) queries.User); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(queries.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, queries.CreateUserParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStore_CreateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUser'
type MockStore_CreateUser_Call struct {
	*mock.Call
}

// CreateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - arg queries.CreateUserParams
func (_e *MockStore_Expecter) CreateUser(ctx interface{}, arg interface{}) *MockStore_CreateUser_Call {
	return &MockStore_CreateUser_Call{Call: _e.mock.On("CreateUser", ctx, arg)}
}

func (_c *MockStore_CreateUser_Call) Run(run func(ctx context.Context, arg queries.CreateUserParams)) *MockStore_CreateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(queries.CreateUserParams))
	})
	return _c
}

func (_c *MockStore_CreateUser_Call) Return(_a0 queries.User, _a1 error) *MockStore_CreateUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStore_CreateUser_Call) RunAndReturn(run func(context.Context, queries.CreateUserParams) (queries.User, error)) *MockStore_CreateUser_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteUser provides a mock function with given fields: ctx, id
func (_m *MockStore) DeleteUser(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStore_DeleteUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteUser'
type MockStore_DeleteUser_Call struct {
	*mock.Call
}

// DeleteUser is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockStore_Expecter) DeleteUser(ctx interface{}, id interface{}) *MockStore_DeleteUser_Call {
	return &MockStore_DeleteUser_Call{Call: _e.mock.On("DeleteUser", ctx, id)}
}

func (_c *MockStore_DeleteUser_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockStore_DeleteUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockStore_DeleteUser_Call) Return(_a0 error) *MockStore_DeleteUser_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStore_DeleteUser_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *MockStore_DeleteUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetUser provides a mock function with given fields: ctx, id
func (_m *MockStore) GetUser(ctx context.Context, id uuid.UUID) (queries.User, error) {
	ret := _m.Called(ctx, id)

	var r0 queries.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (queries.User, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) queries.User); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(queries.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStore_GetUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUser'
type MockStore_GetUser_Call struct {
	*mock.Call
}

// GetUser is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockStore_Expecter) GetUser(ctx interface{}, id interface{}) *MockStore_GetUser_Call {
	return &MockStore_GetUser_Call{Call: _e.mock.On("GetUser", ctx, id)}
}

func (_c *MockStore_GetUser_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockStore_GetUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockStore_GetUser_Call) Return(_a0 queries.User, _a1 error) *MockStore_GetUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStore_GetUser_Call) RunAndReturn(run func(context.Context, uuid.UUID) (queries.User, error)) *MockStore_GetUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserByEmail provides a mock function with given fields: ctx, email
func (_m *MockStore) GetUserByEmail(ctx context.Context, email string) (queries.User, error) {
	ret := _m.Called(ctx, email)

	var r0 queries.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (queries.User, error)); ok {
		return rf(ctx, email)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) queries.User); ok {
		r0 = rf(ctx, email)
	} else {
		r0 = ret.Get(0).(queries.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStore_GetUserByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByEmail'
type MockStore_GetUserByEmail_Call struct {
	*mock.Call
}

// GetUserByEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *MockStore_Expecter) GetUserByEmail(ctx interface{}, email interface{}) *MockStore_GetUserByEmail_Call {
	return &MockStore_GetUserByEmail_Call{Call: _e.mock.On("GetUserByEmail", ctx, email)}
}

func (_c *MockStore_GetUserByEmail_Call) Run(run func(ctx context.Context, email string)) *MockStore_GetUserByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockStore_GetUserByEmail_Call) Return(_a0 queries.User, _a1 error) *MockStore_GetUserByEmail_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStore_GetUserByEmail_Call) RunAndReturn(run func(context.Context, string) (queries.User, error)) *MockStore_GetUserByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// ListUsers provides a mock function with given fields: ctx
func (_m *MockStore) ListUsers(ctx context.Context) ([]queries.User, error) {
	ret := _m.Called(ctx)

	var r0 []queries.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]queries.User, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []queries.User); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]queries.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStore_ListUsers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListUsers'
type MockStore_ListUsers_Call struct {
	*mock.Call
}

// ListUsers is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockStore_Expecter) ListUsers(ctx interface{}) *MockStore_ListUsers_Call {
	return &MockStore_ListUsers_Call{Call: _e.mock.On("ListUsers", ctx)}
}

func (_c *MockStore_ListUsers_Call) Run(run func(ctx context.Context)) *MockStore_ListUsers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockStore_ListUsers_Call) Return(_a0 []queries.User, _a1 error) *MockStore_ListUsers_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStore_ListUsers_Call) RunAndReturn(run func(context.Context) ([]queries.User, error)) *MockStore_ListUsers_Call {
	_c.Call.Return(run)
	return _c
}

// Ping provides a mock function with given fields: ctx
func (_m *MockStore) Ping(ctx context.Context) error {
	ret := _m.Called(ctx)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStore_Ping_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Ping'
type MockStore_Ping_Call struct {
	*mock.Call
}

// Ping is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockStore_Expecter) Ping(ctx interface{}) *MockStore_Ping_Call {
	return &MockStore_Ping_Call{Call: _e.mock.On("Ping", ctx)}
}

func (_c *MockStore_Ping_Call) Run(run func(ctx context.Context)) *MockStore_Ping_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockStore_Ping_Call) Return(_a0 error) *MockStore_Ping_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStore_Ping_Call) RunAndReturn(run func(context.Context) error) *MockStore_Ping_Call {
	_c.Call.Return(run)
	return _c
}

// WithConfiguredTx provides a mock function with given fields: ctx, options, fn
func (_m *MockStore) WithConfiguredTx(ctx context.Context, options *sql.TxOptions, fn store.TxFn) error {
	ret := _m.Called(ctx, options, fn)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *sql.TxOptions, store.TxFn) error); ok {
		r0 = rf(ctx, options, fn)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStore_WithConfiguredTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WithConfiguredTx'
type MockStore_WithConfiguredTx_Call struct {
	*mock.Call
}

// WithConfiguredTx is a helper method to define mock.On call
//   - ctx context.Context
//   - options *sql.TxOptions
//   - fn store.TxFn
func (_e *MockStore_Expecter) WithConfiguredTx(ctx interface{}, options interface{}, fn interface{}) *MockStore_WithConfiguredTx_Call {
	return &MockStore_WithConfiguredTx_Call{Call: _e.mock.On("WithConfiguredTx", ctx, options, fn)}
}

func (_c *MockStore_WithConfiguredTx_Call) Run(run func(ctx context.Context, options *sql.TxOptions, fn store.TxFn)) *MockStore_WithConfiguredTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*sql.TxOptions), args[2].(store.TxFn))
	})
	return _c
}

func (_c *MockStore_WithConfiguredTx_Call) Return(_a0 error) *MockStore_WithConfiguredTx_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStore_WithConfiguredTx_Call) RunAndReturn(run func(context.Context, *sql.TxOptions, store.TxFn) error) *MockStore_WithConfiguredTx_Call {
	_c.Call.Return(run)
	return _c
}

// WithTx provides a mock function with given fields: ctx, fn
func (_m *MockStore) WithTx(ctx context.Context, fn store.TxFn) error {
	ret := _m.Called(ctx, fn)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, store.TxFn) error); ok {
		r0 = rf(ctx, fn)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStore_WithTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WithTx'
type MockStore_WithTx_Call struct {
	*mock.Call
}

// WithTx is a helper method to define mock.On call
//   - ctx context.Context
//   - fn store.TxFn
func (_e *MockStore_Expecter) WithTx(ctx interface{}, fn interface{}) *MockStore_WithTx_Call {
	return &MockStore_WithTx_Call{Call: _e.mock.On("WithTx", ctx, fn)}
}

func (_c *MockStore_WithTx_Call) Run(run func(ctx context.Context, fn store.TxFn)) *MockStore_WithTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(store.TxFn))
	})
	return _c
}

func (_c *MockStore_WithTx_Call) Return(_a0 error) *MockStore_WithTx_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStore_WithTx_Call) RunAndReturn(run func(context.Context, store.TxFn) error) *MockStore_WithTx_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockStore creates a new instance of MockStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStore {
	mock := &MockStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
