apiVersion: v1
kind: Service
metadata:
  name: postgres-dev
  labels:
    app.kubernetes.io/name: postgres-dev
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/name: postgres-dev
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-dev-init
  labels:
    app.kubernetes.io/name: postgres-dev
data:
  init-dbs.sh: |
    #!/bin/bash

    set -eu

    function create_user_and_database() {
      local database=$1
      echo "  Creating '$database'"
      psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
          CREATE DATABASE $database;
          GRANT ALL PRIVILEGES ON DATABASE $database TO $POSTGRES_USER;
    EOSQL
    }

    if [ -n "$POSTGRES_MULTIPLE_DATABASES" ]; then
      echo "Multiple database creation requested: $POSTGRES_MULTIPLE_DATABASES"
      for db in $(echo $POSTGRES_MULTIPLE_DATABASES | tr ',' ' '); do
        create_user_and_database $db
      done
      echo "Multiple databases created"
    fi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-dev
  labels:
    app.kubernetes.io/name: postgres-dev
spec:
  replicas: 1
  serviceName: postgres-dev
  selector:
    matchLabels:
      app.kubernetes.io/name: postgres-dev
  template:
    metadata:
      labels:
        app.kubernetes.io/name: postgres-dev
    spec:
      containers:
        - name: postgres-dev
          image: postgres:15.1-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
            - name: POSTGRES_DB
              value: postgres
            - name: POSTGRES_MULTIPLE_DATABASES
              value: book_svc
          livenessProbe:
            exec:
              command: ["pg_isready", "-U", "postgres", "-d", "postgres"]
            initialDelaySeconds: 5
          volumeMounts:
            - name: postgres-dev
              mountPath: /var/lib/postgres-devql/data
            - name: postgres-dev-init
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: postgres-dev-init
          configMap:
            name: postgres-dev-init
  volumeClaimTemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: postgres-dev
        labels:
          app.kubernetes.io/name: postgres-dev
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
