apiVersion: v1
kind: Service
metadata:
  name: postgres-dev
  labels:
    app.kubernetes.io/name: postgres-dev
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/name: postgres-dev
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-dev
  labels:
    app.kubernetes.io/name: postgres-dev
spec:
  replicas: 1
  serviceName: postgres-dev
  selector:
    matchLabels:
      app.kubernetes.io/name: postgres-dev
  template:
    metadata:
      labels:
        app.kubernetes.io/name: postgres-dev
    spec:
      containers:
        - name: postgres-dev
          image: postgres:15.1-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
            - name: POSTGRES_DB
              value: book_svc
          livenessProbe:
            exec:
              command: ["pg_isready", "-U", "postgres", "-d", "book_svc"]
            initialDelaySeconds: 5
          volumeMounts:
            - name: postgres-dev
              mountPath: /var/lib/postgres-devql/data
  volumeClaimTemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: postgres-dev
        labels:
          app.kubernetes.io/name: postgres-dev
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
