apiVersion: v1
kind: Service
metadata:
  name: service-template
spec:
  selector:
    app.kubernetes.io/name: service-template
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-template
  labels:
    app.kubernetes.io/name: service-template
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: service-template
  template:
    metadata:
      labels:
        app.kubernetes.io/name: service-template
    spec:
      containers:
        - name: service-template
          image: fotiadism/service-template
          ports:
            - containerPort: 8080
          env:
            - name: PSQL_HOST
              value: postgres
            - name: PSQL_PORT
              value: "5432"
            - name: PSQL_USER
              value: postgres
            - name: PSQL_PASS
              value: postgres
            - name: PSQL_DBNAME
              value: book_svc
            - name: REDIS_HOST
              value: redis
            - name: REDIS_PORT
              value: "6379"
            - name: SERVER_REFLECTION
              value: "true"
            - name: OTEL_SERVICE_NAME
              value: book-svc
            - name: OTEL_EXPORTER_ADDR
              value: otel-collector-grpc:4317
            - name: OTEL_SDK_DISABLED
              value: "true"
          livenessProbe:
            grpc:
              port: 8080
              service: liveness
            initialDelaySeconds: 5
          readinessProbe:
            grpc:
              port: 8080
              service: readiness
            initialDelaySeconds: 5
