// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package queries

import (
	"time"

	"github.com/google/uuid"
)

type Author struct {
	ID        uuid.UUID
	Name      string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Book struct {
	ID        uuid.UUID
	Title     string
	AuthorID  uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
}
