// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package queries

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateAuthor(ctx context.Context, arg CreateAuthorParams) (Author, error)
	CreateBook(ctx context.Context, arg CreateBookParams) (Book, error)
	CreateBookReview(ctx context.Context, arg CreateBookReviewParams) (BookReview, error)
	DeleteAuthor(ctx context.Context, id uuid.UUID) error
	DeleteBook(ctx context.Context, id uuid.UUID) error
	GetAuthor(ctx context.Context, id uuid.UUID) (Author, error)
	GetBook(ctx context.Context, id uuid.UUID) (Book, error)
	ListAuthors(ctx context.Context) ([]Author, error)
	ListBooks(ctx context.Context) ([]Book, error)
	UpdateAuthor(ctx context.Context, arg UpdateAuthorParams) (Author, error)
	UpdateBook(ctx context.Context, arg UpdateBookParams) (Book, error)
}

var _ Querier = (*Queries)(nil)
