// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package queries

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateAuthor(ctx context.Context, arg CreateAuthorParams) error
	CreateBook(ctx context.Context, arg CreateBookParams) error
	DeleteAuthor(ctx context.Context, id uuid.UUID) error
	DeleteBook(ctx context.Context, id uuid.UUID) error
	GetAuthor(ctx context.Context, id uuid.UUID) (Author, error)
	GetBook(ctx context.Context, id uuid.UUID) (Book, error)
	ListAuthors(ctx context.Context) ([]Author, error)
	ListBooks(ctx context.Context) ([]Book, error)
}

var _ Querier = (*Queries)(nil)
