apiVersion: v1
kind: Service
metadata:
  name: loki
spec:
  selector:
    app.kubernetes.io/name: loki
  ports:
    - name: loki
      port: 3100
      targetPort: 3100
      protocol: TCP
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-config
  labels:
    app.kubernetes.io/name: loki
data:
  loki.yaml: |
    auth_enabled: false

    server:
      http_listen_port: 3100

    common:
      instance_addr: 0.0.0.0
      path_prefix: /var/loki
      storage:
        filesystem:
          chunks_directory: /var/loki/chunks
          rules_directory: /var/loki/rules
      replication_factor: 1
      ring:
        kvstore:
          store: inmemory

    schema_config:
      configs:
        - from: 2024-01-01
          store: tsdb
          object_store: filesystem
          schema: v13
          index:
            prefix: index_
            period: 24h

    distributor:
      otlp_config:
        default_resource_attributes_as_index_labels:
          - service.name
          - service.instance.id
          - deployment.environment.name
          - cloud.region
          - cloud.availability_zone
          - k8s.cluster.name
          - k8s.namespace.name
          - k8s.replicaset.name
          - k8s.deployment.name
          - k8s.statefulset.name
          - k8s.daemonset.name
          - k8s.cronjob.name
          - k8s.job.name
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: loki
  labels:
    app.kubernetes.io/name: loki
spec:
  replicas: 1
  serviceName: loki
  selector:
    matchLabels:
      app.kubernetes.io/name: loki
  template:
    metadata:
      labels:
        app.kubernetes.io/name: loki
    spec:
      containers:
        - name: loki
          image: grafana/loki:3.4
          args: ["-config.file=/etc/loki/loki.yaml", "-target=all"]
          ports:
            - name: loki
              containerPort: 3100
          livenessProbe:
            httpGet:
              path: /config
              port: loki
            initialDelaySeconds: 5
          readinessProbe:
            httpGet:
              path: /ready
              port: loki
            initialDelaySeconds: 5
          volumeMounts:
            - name: loki
              mountPath: /var/loki
            - name: loki-config
              mountPath: /etc/loki/
      volumes:
        - name: loki-config
          configMap:
            name: loki-config
  volumeClaimTemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: loki
        labels:
          app.kubernetes.io/name: loki
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
