apiVersion: v1
kind: Service
metadata:
  name: otel-collector
spec:
  selector:
    app.kubernetes.io/name: otel-collector
  ports:
    - name: otlp-http
      port: 4318
      protocol: TCP
      targetPort: 4318
---
apiVersion: v1
kind: Service
metadata:
  name: otel-collector-grpc
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/name: otel-collector
  ports:
    - name: otlp-grpc
      port: 4317
      protocol: TCP
      targetPort: 4317
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector
  labels:
    app.kubernetes.io/name: otel-collector
data:
  config.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317

    processors:

    extensions:
      health_check:
        endpoint: 0.0.0.0:13133
        path: /healthz

    exporters:
      otlp/jaeger:
        endpoint: jaeger:4317
        tls:
          insecure: true
      otlp/tempo:
        endpoint: tempo:4317
        tls:
          insecure: true
      otlphttp/loki:
        endpoint: http://loki:3100/otlp
      otlphttp/prometheus:
        endpoint: http://prometheus:9090/api/v1/otlp
      otlphttp/mimir:
        endpoint: http://mimir:9009/otlp
      debug:

    service:
      extensions: [health_check]
      pipelines:
        traces:
          receivers: [otlp]
          processors: []
          exporters: [otlp/tempo]

        metrics:
          receivers: [otlp]
          processors: []
          exporters: [otlphttp/mimir]

        logs:
          receivers: [otlp]
          processors: []
          exporters: [otlphttp/loki]
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: otel-collector
  labels:
    app.kubernetes.io/name: otel-collector
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: otel-collector
  template:
    metadata:
      labels:
        app.kubernetes.io/name: otel-collector
    spec:
      containers:
        - name: otel-collector
          image: otel/opentelemetry-collector-contrib:0.115.1
          args: ["--config=/etc/otel/config.yaml"]
          ports:
            - containerPort: 1888 # pprof extension
            - containerPort: 8888 # Prometheus metrics exposed by the Collector
            - containerPort: 8889 # Prometheus exporter metrics
            - containerPort: 13133 # health_check extension
            - containerPort: 4317 # OTLP gRPC receiver
            - containerPort: 4318 # OTLP http receiver
            - containerPort: 55679 # zpages extension
          livenessProbe:
            httpGet:
              port: 13133
              path: /healthz
            initialDelaySeconds: 5
          volumeMounts:
            - name: otel-collector
              mountPath: /etc/otel/
      volumes:
        - name: otel-collector
          configMap:
            name: otel-collector
