apiVersion: v1
kind: Service
metadata:
  name: tempo
spec:
  selector:
    app.kubernetes.io/name: tempo
  ports:
    - name: tempo
      port: 3200
      targetPort: 3200
      protocol: TCP
    - name: otel-grpc
      port: 4317
      targetPort: 4317
      protocol: TCP
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: tempo-config
  labels:
    app.kubernetes.io/name: tempo
data:
  tempo.yaml: |
    server:
      http_listen_port: 3200

    stream_over_http_enabled: true

    distributor:
      receivers:
        otlp:
          protocols:
            grpc:
              endpoint: 0.0.0.0:4317

    storage:
      trace:
        backend: local
        wal:
          path: /var/tempo/wal
        local:
          path: /var/tempo/blocks
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: tempo
  labels:
    app.kubernetes.io/name: tempo
spec:
  replicas: 1
  serviceName: tempo
  selector:
    matchLabels:
      app.kubernetes.io/name: tempo
  template:
    metadata:
      labels:
        app.kubernetes.io/name: tempo
    spec:
      initContainers:
        - name: tempo-init
          image: grafana/tempo:2.7.1
          command: ["chown", "-R", "10001:10001", "/var/tempo"]
          volumeMounts:
            - name: tempo
              mountPath: /var/tempo
          securityContext:
            runAsUser: 0
            runAsGroup: 0
      containers:
        - name: tempo
          image: grafana/tempo:2.7.1
          args: ["-config.file=/etc/tempo/tempo.yaml"]
          ports:
            - name: tempo
              containerPort: 3200
            - name: otel-grpc
              containerPort: 4317
          livenessProbe:
            httpGet:
              path: /status/version
              port: tempo
            initialDelaySeconds: 5
          readinessProbe:
            httpGet:
              path: /ready
              port: tempo
            initialDelaySeconds: 5
          volumeMounts:
            - name: tempo
              mountPath: /var/tempo
            - name: tempo-config
              mountPath: /etc/tempo/
      volumes:
        - name: tempo-config
          configMap:
            name: tempo-config
  volumeClaimTemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: tempo
        labels:
          app.kubernetes.io/name: tempo
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
