apiVersion: v1
kind: Service
metadata:
  name: swagger
spec:
  selector:
    app.kubernetes.io/name: swagger
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: swagger
  labels:
    app.kubernetes.io/name: swagger
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: swagger
  template:
    metadata:
      labels:
        app.kubernetes.io/name: swagger
    spec:
      containers:
        - name: swagger
          image: swaggerapi/swagger-ui:v5.18.3
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
            - name: SWAGGER_JSON_URL
              value: http://localhost:8080/api/docs/book/v1/book.swagger.json
