// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package queries

import (
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
)

type UserScope string

const (
	UserScopeUser  UserScope = "user"
	UserScopeAdmin UserScope = "admin"
)

func (e *UserScope) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserScope(s)
	case string:
		*e = UserScope(s)
	default:
		return fmt.Errorf("unsupported scan type for UserScope: %T", src)
	}
	return nil
}

type NullUserScope struct {
	UserScope UserScope
	Valid     bool // Valid is true if UserScope is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserScope) Scan(value interface{}) error {
	if value == nil {
		ns.UserScope, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserScope.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserScope) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserScope), nil
}

type Post struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Title     string
	Text      string
	Likes     int32
	CreatedAt time.Time
	UpdatedAt time.Time
}

type PostComment struct {
	ID        uuid.UUID
	PostID    uuid.UUID
	UserID    uuid.UUID
	Text      string
	Likes     int32
	CreatedAt time.Time
	UpdatedAt time.Time
}

type User struct {
	ID        uuid.UUID
	Email     string
	Password  string
	Scope     UserScope
	Active    bool
	CreatedAt time.Time
	UpdatedAt time.Time
}
