apiVersion: v1
kind: Service
metadata:
  name: jaeger
spec:
  selector:
    app.kubernetes.io/name: jaeger
  ports:
    - name: web-ui
      port: 16686
      targetPort: 16686
      protocol: TCP
    - name: otlp-grpc
      port: 4317
      targetPort: 4317
      protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger
  labels:
    app.kubernetes.io/name: jaeger
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: jaeger
  template:
    metadata:
      labels:
        app.kubernetes.io/name: jaeger
    spec:
      containers:
        - name: jaeger
          image: jaegertracing/all-in-one:1.60
          ports:
            - name: otlp-grpc
              containerPort: 4317
            - name: web-ui
              containerPort: 16686
            - name: admin
              containerPort: 16687
