apiVersion: v1
kind: Service
metadata:
  name: prometheus
spec:
  selector:
    app.kubernetes.io/name: prometheus
  ports:
    - port: 9090
      targetPort: 9090
      protocol: TCP
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus
  labels:
    app.kubernetes.io/name: prometheus
data:
  prometheus.yaml: |
    otlp:
      promote_resource_attributes:
        - service.name
        - service.instance.id
        - service.namespace
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  labels:
    app.kubernetes.io/name: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: prometheus
  template:
    metadata:
      labels:
        app.kubernetes.io/name: prometheus
    spec:
      containers:
        - name: prometheus
          image: prom/prometheus:v3.0.1
          args:
            - --web.enable-otlp-receiver
            - --config.file=/etc/prometheus/prometheus.yaml
          ports:
            - containerPort: 9090
          livenessProbe:
            httpGet:
              port: 9090
              path: /-/healthy
            initialDelaySeconds: 5
          volumeMounts:
            - name: prometheus
              mountPath: /etc/prometheus/
      volumes:
        - name: prometheus
          configMap:
            name: prometheus
